### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by 920225063** [realcrane/Human-Trajectory-Prediction-via-Neural-Social-Physics#1]
Your work is great！
When I was running the train_nsp_wo.py, I encountered a problem that I couldn't solve after debugging for a long time.
in model_nsp_wo.py：
if area[i, 0, 0] != area[i, 0, 1] and area[i, 1, 0] == area[i, 1, 1]:
            environment_vision = semantic_map[
                                 torch.min(area[i, 0, 0], area[i, 0, 1]): torch.max(area[i, 0, 0], area[i, 0, 1]),
                                 area[i, 1, 0]]
line 42, in environment
    area[i, 1, 0]]
IndexError: index 1107 is out of bounds for axis 1 with size 1079

**Comment by JiangbeiYue** [comment]
This seems that the loaded environment segmentation map doesn't match the loaded sub-dataset. I guess you might not put complete files in the data file. For example, in the training phase on the SDD, I suggest you check if you put 30 masks in data/SDD/train_masks/ and put the corresponding 30 sub-datasets (.pickle files) in data/SDD/train_pickle. 

A quick debug for the problem is to check if the name of the loaded sub-dataset and the name of the loaded masks (environment segmentation maps) match.

**Comment by MMNavetty** [comment]
quick fix : add sorted when list files :

train_nsp_w.py line 326-328 :
semantic_maps_name_train = sorted(os.listdir(semantic_path_train))
semantic_maps_name_test = sorted(os.listdir(semantic_path_test))
